version: '3.1'
services:

  php:
    build:
      context: ../
      dockerfile: Dockerfile
    image: php-laravel  
    working_dir: /var/www
    volumes:
      - ../:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  nginx:
    image: nginx:alpine
    ports: 
      - 8789:80
    restart: unless-stopped
    volumes: 
      - ../:/var/www
      - ../conf.d:/etc/nginx/conf.d
    depends_on:
      - php 
